project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  open-graph: true
  repo-actions: [issue]
  # navbar:
  #   background: primary
  #   search: true
  #   left:
  #     - text: "Blog"
  #       href: blog/index.qmd
  # sidebar:
    # style: floating
  #   contents:
  #     - section: API
  #       contents: api/*

metadata-files: [nbdev.yml, sidebar.yml, navbar.yml]
# metadata-files: [nbdev.yml]